---
title: "stat_bayes"
output: html_document
date: "2025-11-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
#Csomgagok
library(haven)
library(tidyverse)
library(fitdistrplus)
library(ggplot2)
```


```{r}
#Adat betoltes
insurance_claims <- read_sav("insurance_claims.sav")
```


```{r}
#Kiinduló priorok empririkus becsléséhez az első hónap adatainak a leválasztása
insurance_claims = insurance_claims |>
  sort_by(~list(incident_date))

#káradatok logaritmizálása
insurance_claims$logclaim = log(insurance_claims$claim_amount)
firstmonth = insurance_claims[insurance_claims$incident_date<='2008-01-31',]
claimdata = insurance_claims[insurance_claims$incident_date>'2008-01-31',]

#kiindulo priorok meghatarozasa
log_fixed_var = sd(firstmonth$logclaim)^2 #ismertnek tekintett variancia

muprior = numeric()
sigma2prior = numeric()

muprior[1] = mean(firstmonth$logclaim)
sigma2prior[1] = log_fixed_var/nrow(firstmonth) #várható erték varianciája

#Fügvények a prior paraméterek frissítéséhez
muprior_update = function(mu_prior, sigma2_prior, variance, logclaim) {
  mu_posterior = 1/(1/sigma2_prior+1/variance)*(mu_prior/sigma2_prior+logclaim/variance)
  return(mu_posterior)
}

sigma2prior_update = function(sigma2_prior, variance) {
  sigma2_posterior = ( 1/(1/sigma2_prior+1/variance))
  return(sigma2_posterior)
}

```


```{r}
#Prior paraméterek frissítése minden káresemény után
for (i in 2:nrow(claimdata)) {
  muprior[i] = muprior_update(muprior[i-1], sigma2prior[i-1], log_fixed_var, claimdata$logclaim[i-1])
  sigma2prior[i] = sigma2prior_update(sigma2prior[i-1],log_fixed_var)
}

muprior[4040] = muprior_update(muprior[4039], sigma2prior[4039], log_fixed_var, claimdata$logclaim[4039])
sigma2prior[4040] = sigma2prior_update(sigma2prior[4039],log_fixed_var)


```


```{r}
#feltételezett prior/posterior paraméterek a logaritmikus adatok várható értékére
claimdata$log_mu <- muprior[2:4040]
claimdata$log_sigma2 = sigma2prior[2:4040]

#feltételezett paraméterek a valódi káradatok várható értékére
claimdata$mu = exp(claimdata$log_mu+claimdata$log_sigma2/2)
claimdata$sigma2 = (exp(claimdata$log_sigma2)-1)*exp(2*claimdata$log_mu+claimdata$log_sigma2)

#prediktív paraméterek logaritmizált káradatok eloszlására
claimdata$log_mu_pred <- claimdata$log_mu
claimdata$log_sigma2_pred <- claimdata$log_sigma2+log_fixed_var

#prediktív paraméterek a rendes káradatok eloszlására
claimdata$mu_pred = exp(claimdata$log_mu_pred+claimdata$log_sigma2_pred/2)
claimdata$sigma2_pred = (exp(claimdata$log_sigma2_pred)-1)*
                    exp(2*claimdata$log_mu_pred+claimdata$log_sigma2_pred)


df <- data.frame(E = claimdata$mu_pred, D = sqrt(claimdata$sigma2_pred),
                 E_log = claimdata$log_mu_pred,
                 D_log = sqrt(claimdata$log_sigma2_pred))

```


```{r}
#Optimalizalashoz szukseges fugvenyek definialasa
obj_fn <- function(par) {
  
  alpha <- par[1]
  beta  <- par[2]
  gamma <- par[3]
  
  p_mean  <- df$E * (1 + alpha)
  p_sd    <- df$E + beta * df$D
  p_quant <- gamma * df$E + (1 - gamma) * qlnorm(0.95,meanlog = df$E_log, sdlog = df$D_log)

  d12 <- p_mean - p_sd
  d13 <- p_mean - p_quant
  d23 <- p_sd   - p_quant

  val <- sum(d12^2 + d13^2 + d23^2)

  if (!is.finite(val)) val <- 1e50
  return(val)
}

#Optimalizálás, hogy minden díjelvel átlagosan ugyanazt az eredményt kapjuk
res <- optim(
  par = c(alpha = 0, beta = 1, gamma = 0.5), 
  fn = obj_fn, 
  method = "L-BFGS-B",
  lower = c(alpha = 0.3, beta = 0, gamma = 0),
  upper = c(alpha = 10, beta = 10, gamma = 1),
  control = list(maxit = 20000))

res$par
```


```{r}
#Díjak meghatározása
res$par["alpha"]
x = res$par["alpha"]
y = res$par["beta"]
z = res$par["gamma"] 
kar_val = 0.02

p_mean_x <- df$E * (1 + x) * kar_val
p_sd_y  <- (df$E + y * df$D) * kar_val
p_quant_z <- (z * df$E + (1 - z) *
              qlnorm(0.95, meanlog = df$E_log, sdlog = df$D_log)) * kar_val
prices = data.frame(p_mean = p_mean_x, p_sd = p_sd_y, p_quant = p_quant_z)
```

Lent vannak jobban látható, átskálázott ábrák
```{r}
#feltételezett várható érték alakulása a teljes "populációból" becsülthöz képest

#teljes populációból becsült várható érték
mean_pop = exp(mean(insurance_claims$logclaim) +
          (sd(insurance_claims$logclaim)^2)/2)


ggplot(claimdata, aes(1:4039, mu_pred)) +
  geom_line() +
  geom_line(aes(1:4039,mu)) +
  geom_hline(yintercept = mean_pop, color = "green") +
  geom_hline(yintercept = mean(claimdata$claim_amount), color = "red") +
  ylim(0, 80)
  
```

```{r}
#feltételezett szórás alakulása a teljes "populációból" becsülthöz képest

#teljes populációból becsült szórás
var_pop = (exp(sd(insurance_claims$logclaim)^2) - 1) * exp(2 * mean(insurance_claims$logclaim) + sd(insurance_claims$logclaim)^2)



ggplot(claimdata, aes(1:4039, sqrt(sigma2_pred))) +
  geom_line() +
  geom_line(aes(1:4039,sqrt(sigma2))) +
  geom_hline(yintercept = sqrt(var_pop), color = "green") +
  geom_hline(yintercept = sd(claimdata$claim_amount), color = "red")
```


```{r}
#Eltolt skálán a jobb láthatóság kedvéért

# skálaeltolás
scale_factor_mu <- 2

ggplot(claimdata, aes(x = 1:4039)) +
  geom_line(aes(y = mu_pred), color = "blue") +
  geom_line(aes(y = mu * scale_factor_mu), color = "orange") +  # scaled mu
  
  scale_y_continuous(
    name = "Predictive Mean (mu_pred)",
    #limits = c(0, 80),
    sec.axis = sec_axis(~ . / scale_factor_mu, name = "Posterior Mean (mu)")
  ) +
  
  geom_hline(yintercept = mean_pop, color = "green") +
  geom_hline(yintercept = mean(claimdata$claim_amount), color = "red")

```

```{r}
scale_factor_sigma <- 70

ggplot(claimdata, aes(x = 1:4039)) +
  geom_line(aes(y = sqrt(sigma2_pred)), color = "blue") +
  geom_line(aes(y = sqrt(sigma2) * scale_factor_sigma), color = "orange") +  
  
  scale_y_continuous(
    name = "Predictive Standard deviation sqrt(sigma2_pred)",
    #limits = c(0, 80),
    sec.axis = sec_axis(~ . / scale_factor_sigma, name = "Posterior Standard Deviation sqrt(sigma2)")
  ) +
  
  geom_hline(yintercept = sqrt(var_pop), color = "green") +
  geom_hline(yintercept = sd(claimdata$claim_amount), color = "red")

```

```{r}
ggplot(prices, aes(x = 1:4039)) +
  geom_line(aes(y= p_mean, color = "red")) +
  geom_line(aes(y= p_sd, color = "green")) +
  geom_line(aes(y= p_quant, color = "blue"))
```

```{r}
scale_factor_log <- 20
#claimdata_short = claimdata[1:1000,]
ggplot(claimdata, aes(x = 1:4039)) +
  geom_line(aes(y = log_mu), color = "blue") +
  #geom_line(aes(y = log_sigma2 * scale_factor), color = "orange") +  
  #geom_line(aes(y = logclaim)) +
  
  scale_y_continuous(
    name = "Log Mean Posterior (log_mu)"#,
    #limits = c(0, 80),
    #sec.axis = sec_axis(~ . / scale_factor_log, name = "Log Var Posterior (log_sigma2)")
  ) +
  
  geom_hline(yintercept = mean(claimdata$logclaim), color = "green")
```

