
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

li-lee prep:
```{r}
library(dplyr)
library(demography)
library(ggplot2)
library(timetk)
```

State names list
```{r}

states <- c("AL","AR","AZ","CA","CO","CT","DE","FL","GA","IA", "ID",
            "IL","IN","KS","KY","LA","MA", "MD","ME","MI", "MN",
            "MO","MS","MT","NC","ND", "NE","NH","NJ","NM","NV","NY",
            "OH","OK","OR","PA","RI","SC","SD","TN", "TX","UT",
            "VA","VT","WA","WI","WV","WY")

#Alaska es Hawaii-t kivettem mert nincsenek szarazfoldi szomszedos allamaik, tovabbi meg DC is benne volt az adatok kozott igy azt is kivettem mert az nem allam
```

Global variables
```{r}

min_year_global <- 1969 #exp szamok 1969-tol indulnak
max_year_global <- 2019

train_test_border <- 2005

n <- length(states)
```


Create a list from the mx data
```{r}

states_mx <- paste(states,"_bltper_1x1.txt", sep="")

list_of_path_mx <- file.path("~/Desktop/TDK/bltper_1x1", states_mx)

```


mx
```{r}
mx <- list()

for (i in 1:n){
  name_of_states <- paste("mxt_", states[i], sep='')
  
  helper1 = read.table(list_of_path_mx[i], skip = 2, header=T) 
  
   helper1 = helper1 %>%
    filter(Age != "110+") %>%
    filter(Year >= min_year_global & Year <= max_year_global)
  
  helper1$Age = as.numeric(helper1$Age)
  helper1$Year = as.numeric(helper1$Year)
  
  helper1 = helper1 %>%
    filter(Age <= 89)
  
  mx[[i]] <- helper1[, c("Year", "Age", "mx")]
}

names(mx) = paste("mxt_", states, sep='')
```


exp
```{r setup}
exp_data <- "~/Desktop/TDK/us.1969_2023.singleages.through89.90plus.adjusted.txt"

Exp <- read.table(exp_data, stringsAsFactors = FALSE, colClasses = "character", fill = TRUE)

Year_chr         <- substr(Exp$V1, 1, 4)
State            <- substr(Exp$V1, 5, 6)
State_FIPS_chr  <- substr(Exp$V1, 7, 8)
County_FIPS_chr <- substr(Exp$V1, 9, 11)
Race_chr        <- substr(Exp$V2, 1, 1)
Origin_chr      <- substr(Exp$V2, 2, 2)
Sex_chr          <- substr(Exp$V2, 3, 3)
Age_chr          <- substr(Exp$V2, 4, 5)
Pop_chr          <- substr(Exp$V2, 6, 14)

Year         <- as.integer(Year_chr)
State_FIPS  <- as.integer(State_FIPS_chr)
County_FIPS <- as.integer(County_FIPS_chr)
Race        <- as.integer(Race_chr)
Origin      <- as.integer(Origin_chr)
Sex          <- as.integer(Sex_chr)
Age          <- as.integer(Age_chr)
Pop          <- as.integer(Pop_chr)

Exp<- data.frame(
  State = State,
  State_FIPS = State_FIPS,
  Year = Year,
  County_FIPS = County_FIPS,
  Race = Race,
  Origin = Origin,
  Sex = Sex,
  Age = Age,
  Pop = Pop,
  stringsAsFactors = FALSE
)

Exp <- Exp[Exp$Year <= 2019 & Exp$Age <= 89 & Exp$State !="AK" & Exp$State !="HI" & Exp$State !="DC" & Exp$State !="KR",]

# Aggregate: sum population across sexes for each Year x State x Age
Exp <- aggregate(Pop ~  State + Year + Age, data = Exp, FUN = function(x) sum(x, na.rm = TRUE))
unique(Exp$State)
# sort result
Exp <- Exp[order(Exp$State, Exp$Year, Exp$Age), ]
#sub state sorting
exposures <- list()

for(s in states){
  sub <- Exp[Exp$State == s, c("Year","Age","Pop")]
  exposures[[s]] <- sub
}

names(exposures) = paste("Ext_", states, sep='')
```

mortality_data_raw
```{r}
mortality_data_raw <- bind_rows(mx, .id = "state")
mortality_data_raw <- mortality_data_raw %>%
  mutate(state = sub("^mxt_", "", state))                  

mortality_data_raw <- mortality_data_raw %>% 
  rename(states = state)

train_test_border <- 2005
num_steps_fc <- max_year_global-train_test_border+1

```

mortality_data_raw es exp-bol dtx szamolasa li-lee-hez
```{r}
helper <- mortality_data_raw
helper$exp <- Exp$Pop
helper$dx <- helper$mx*helper$exp+0.5
helper$mx <- helper$dx/helper$exp


mortality_data <- helper[,c(1,2,3,4)]
helper <- helper[,c(1,2,3,6)]


deaths <- list()
for(s in states){
  sub <- helper[helper$states == s, c("Year","Age","dx")]
  deaths[[s]] <- sub
}

names(deaths) = paste("Dtx_", states, sep='')
```


li-lee_models:
```{r}
# Data preprocess
library(dplyr)
library(readxl)

# LC model
library(demography)
library(StMoMo)

# Forecast
library(forecast)

# VAR dependencies
library(sparsevar)

# SDPD dependencies
library(rnaturalearthdata)
library(rnaturalearth)
library(sf)
library(spdep)
library(cepiigeodist)
library(Matrix)

# SARIMA dependencies
library(starma)

# ESTF dependencies
library(Matrix)
library(MASS)
library(glmnet)
library(bigstep)

#DPLM
library(plm)
library(fastDummies)

#install.packages("remotes")
library("remotes")
remotes::install_github("RobbenJ/MultiMoMo")
library("MultiMoMo")
```

```{r}
mortality_data$mx <- log(mortality_data$mx) 
mortality_data <- mortality_data %>% rename(lmxt = mx) %>% rename(year = Year)
#%>% rename(states = state)

results_list <- list()
mse_results_list <- list()

train_test_border <- 2005
num_steps_fc <- max_year_global-train_test_border+1
```

Define data frames
```{r}
test_long <- mortality_data %>% filter(year >= train_test_border)
train_long <- mortality_data %>%  filter(year < train_test_border) 

results_df_long <- test_long # Ezt fogjuk feltölteni a modellek predikcióival.
```

Create train test sets
```{r}

LL_train_test_sets_list <- Train_test_sets(deaths,
                                            exposures,
                                            train_test_border,
                                            states)

```

Preprocess the data for LL models
```{r}

LL_result_list <- LL_preprocess_and_models(LL_train_test_sets_list)
 
#Organize and save parameters 
 LL_Ax <- LL_result_list$LL_models$A.x
 LL_Bx <- LL_result_list$LL_models$B.x
 LL_Kt <- LL_result_list$LL_models$K.t
 
#Create separate data frames with column name "x"
 LL_Ax <- data.frame(x = LL_Ax)
 LL_Bx <- data.frame(x = LL_Bx)
 LL_Kt <- data.frame(x = LL_Kt)
 
 parameter_list <- LL_country_spec_parameters(LL_result_list$kt, LL_result_list$bx)
 
 kt_long <- parameter_list$kt
 bx_long <- parameter_list$bx

```

Save parameters
```{r}
 write.csv(LL_Ax,
           "~/Desktop/TDK/output/LL_Ax.csv",
           row.names=FALSE)
 
 write.csv(LL_Bx,
           "~/Desktop/TDK/output/LL_Bx.csv",
           row.names=FALSE)
 
 write.csv(LL_Kt,
           "~/Desktop/TDK/output/LL_Kt.csv",
           row.names=FALSE)
 
 
 write.csv(kt_long,
           "~/Desktop/TDK/output/LL_kt_long.csv",
           row.names=FALSE)
 
 write.csv(bx_long,
           "~/Desktop/TDK/output/LL_bx_long.csv",
           row.names=FALSE)

```

Load LL parameters
```{r}
setwd("~/Desktop/TDK/OLD_outputs/output_2005_split_newest_old")
LL_Ax <- read.csv("LL_Ax.csv")
LL_Bx <- read.csv("LL_Bx.csv")
LL_Kt <- read.csv("LL_Kt.csv")
kt_long <- read.csv("LL_kt_long.csv")
bx_long <- read.csv("LL_bx_long.csv")
```

models
```{r}
#FC the common Kt parameter
Kt_fc_m <- rwf(LL_Kt, drift = TRUE, h = num_steps_fc)
Kt_fc <- as.vector(Kt_fc_m$mean)
Kt_fc <- data.frame(x = Kt_fc)
```

```{r}
#RWD - LL esetében csak az utolsó értéket meghosszabbítjuk.
print("Forecast with RWD")

x_rwd_results <- RWD_FC(Ax=LL_Ax,
                          Bx=LL_Bx,
                          kt=kt_long,
                          bx=bx_long,
                          Kt_comm=LL_Kt, 
                          Kt_fc=Kt_fc,
                          train_data=train_long,
                          test_data=results_df_long,
                          num_steps_fc=num_steps_fc,
                          jumpoff=TRUE,
                          param=NULL,
                          LC=FALSE)

#ARIMA
print("Forecast with ARIMA")

x_arima_results <- ARIMA_FC(Ax=LL_Ax,
                            Bx=LL_Bx,
                            kt=kt_long,
                            bx=bx_long,
                            Kt_comm=LL_Kt, 
                            Kt_fc=Kt_fc,
                            train_data=train_long,
                            test_data=results_df_long,
                            num_steps_fc=num_steps_fc,
                            jumpoff=TRUE,
                            param=NULL,
                            LC=FALSE,
                            stac=TRUE) # Stacionernek tegyük fel az adatot, hogy ne diferenciázzon a fv.


#VAR
print("Forecast with VAR")

x_var_results <- VAR_FC(Ax=LL_Ax,
                          Bx=LL_Bx,
                          kt=kt_long,
                          bx=bx_long,
                          Kt_comm=LL_Kt, 
                          Kt_fc=Kt_fc,
                          train_data=train_long,
                          test_data=results_df_long,
                          num_steps_fc=num_steps_fc,
                          jumpoff=TRUE,
                          param=NULL,
                          LC=FALSE,
                          opt=TRUE,
                          difference = FALSE)

#DPLM
print("Forecast with DPLM")

x_dplm_results <- DPLM_FC(Ax=LL_Ax,
                           Bx=LL_Bx,
                           kt=kt_long,
                           bx=bx_long,
                           Kt_comm=LL_Kt, 
                           Kt_fc=Kt_fc,
                           train_data=train_long,
                           test_data=results_df_long,
                           num_steps_fc=num_steps_fc,
                           jumpoff=TRUE,
                           LC=FALSE,
                           opt=TRUE,
                           difference = FALSE)

#SDPD
print("Forecast with SDPD")
kt=kt_long
x_sdpd_results <- SDPD_FC(Ax=LL_Ax,
                           Bx=LL_Bx,
                           kt=kt_long,
                           bx=bx_long,
                           Kt_comm=LL_Kt, 
                           Kt_fc=Kt_fc,
                           train_data=train_long,
                           test_data=results_df_long,
                           num_steps_fc=num_steps_fc,
                           jumpoff=TRUE,
                           param=NULL,
                           LC=FALSE,
                           opt=TRUE,
                           difference=FALSE)


#STARIMA
print("Forecast with SARIMA")

kt=kt_long
x_starima_results <- STARIMA_FC(Ax=LL_Ax,
                              Bx=LL_Bx,
                              kt=kt_long,
                              bx=bx_long,
                              Kt_comm=LL_Kt, 
                              Kt_fc=Kt_fc,
                              train_data=train_long,
                              test_data=results_df_long,
                              num_steps_fc=num_steps_fc,
                              jumpoff=TRUE,
                              param=NULL,
                              LC=FALSE,
                              opt=TRUE,
                              difference=FALSE)

#ESTF
print("Forecast with ESTF")

x_estf_results <- ESTF_FC(Ax=LL_Ax,
                           Bx=LL_Bx,
                           kt=kt_long,
                           bx=bx_long,
                           Kt_comm=LL_Kt, 
                           Kt_fc=Kt_fc,
                           train_data=train_long,
                           test_data=results_df_long,
                           num_steps_fc=num_steps_fc,
                           jumpoff=TRUE,
                           param=NULL,
                           LC=FALSE,
                           selected_models=c(1,2,5,6),
                           difference=FALSE)

```

```{r}
### Combine results
results_df_long <- cbind(results_df_long,
                         lmxt_rwd = x_rwd_results$test_data$lmxt_rwd,
                         error_rwd = x_rwd_results$test_data$error_rwd,
                         lmxt_arima = x_arima_results$test_data$lmxt_arima,
                         error_arima = x_arima_results$test_data$error_arima,
                         lmxt_var = x_var_results$test_data$lmxt_var,
                         error_var = x_var_results$test_data$error_var,
                         lmxt_dplm = x_dplm_results$test_data$lmxt_dplm,
                         error_dplm = x_dplm_results$test_data$error_dplm,
                         lmxt_sdpd = x_sdpd_results$test_data$lmxt_sdpd,
                         error_sdpd= x_sdpd_results$test_data$error_sdpd,
                         lmxt_starima = x_starima_results$test_data$lmxt_starima,
                         error_starima = x_starima_results$test_data$error_starima,
                         lmxt_estf = x_estf_results$test_data$lmxt_estf,
                         error_estf = x_estf_results$test_data$error_estf,
                         lmxt_gmm_lsdplm = x_gmm_lsdplm_results$test_data$lmxt_gmm_lsdplm,
                         error_gmm_lsdplm = x_gmm_lsdplm_results$test_data$error_gmm_lsdplm,
                         lmxt_gmm_sdplm = x_gmm_sdplm_results$test_data$lmxt_gmm_sdplm,
                         error_gmm_sdplm = x_gmm_sdplm_results$test_data$error_gmm_sdplm
                         )

# Simple Ensemble
print("Forecast with Ensemble")

results_df_long <- ENSEMBLE_FC(test_data=results_df_long)


# Organize the results

mse <- results_df_long %>% 
  group_by(states) %>%
  summarize(RWD = mean(error_rwd**2),
            ARIMA = mean(error_arima**2),
            STARIMA = mean(error_starima**2),
            VAR = mean(error_var**2),
            SDPLM_QML = mean(error_sdpd**2),
            ESTF = mean(error_estf**2),
            ENSEMBLE_SIMPLE_MEAN= mean(error_ensemble_simple_mean**2),
            ENSEMBLE_TRIMMED_MEAN= mean(error_ensemble_trimmed_mean**2),
            DPLM = mean(error_dplm**2),
            SDPLM_GMM = mean(error_gmm_sdplm**2),
            LSDPLM_GMM = mean(error_gmm_lsdplm**2)
  ) %>%
  print(n = length(countries))

mse$winner_model <- names(mse)[as.matrix(apply(mse[,2:ncol(mse)], 1, which.min))+1]

# Best models
mse_results_list <- mse %>%
  group_by(winner_model) %>%
  count() %>%
  arrange(desc(n))
```


```{r}
# Save final results
write.csv(results_df_long,
          "~/Desktop/TDK/output/LL_forecasts.csv",
          row.names=FALSE)

write.csv(mse_results_list,
          "~/Desktop/TDK/output/LL_aggregated_results.csv",
          row.names=FALSE)

write.csv(mse,
          "~/Desktop/TDK/output/LL_mse_by_countries.csv",
          row.names=FALSE)
```

